__all__ = [
    '_SLEEP',
    '_WAIT_SOCK_READ',
    '_WAIT_SOCK_WRITE',
    '_CLOSE_EVENT_LOOP',
    '_WAIT_SOCK_ACCEPT'
]

_SLEEP = 0x00
_CLOSE_EVENT_LOOP = 0x01
_WAIT_SOCK_READ = 0x02
_WAIT_SOCK_WRITE = 0x03
_WAIT_SOCK_ACCEPT = 0x04

